[versions]
spring-boot = "4.0.1"
spring-dependency-management = "1.1.7"
kotlin = "2.2.20"
lombok = "1.18.42"
mapstruct = "1.6.3"
commons-lang3 = "3.20.0"
spotless = "8.1.0"
google-java-format = "1.31.0"
ktlint = "1.7.1"
jacoco = "0.8.14"
mockk = "1.14.7"
groovy = "5.0.3"
spock = "2.4-groovy-5.0"
platform-commons = "1.0.0-SNAPSHOT"

[libraries]
spring-boot-gradle-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot" }
spring-dependency-management = { module = "io.spring.gradle:dependency-management-plugin", version.ref = "spring-dependency-management" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
